/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32A50X)
#include <gd32a50x_syscfg.h>
#elif defined(CONFIG_SOC_SERIES_GD32C2X1)
#include <gd32c2x1_syscfg.h>
#elif defined(CONFIG_SOC_SERIES_GD32F3X0)
#include <gd32f3x0_syscfg.h>
#elif defined(CONFIG_SOC_SERIES_GD32F4XX)
#include <gd32f4xx_syscfg.h>
#elif defined(CONFIG_SOC_SERIES_GD32F50X)
#include <gd32f50x_syscfg.h>
#elif defined(CONFIG_SOC_SERIES_GD32F527)
#include <gd32f527_syscfg.h>
#elif defined(CONFIG_SOC_SERIES_GD32G5X3)
#include <gd32g5x3_syscfg.h>
#elif defined(CONFIG_SOC_SERIES_GD32H75E)
#include <gd32h75e_syscfg.h>
#elif defined(CONFIG_SOC_SERIES_GD32H7XX)
#include <gd32h7xx_syscfg.h>
#elif defined(CONFIG_SOC_SERIES_GD32L23X)
#include <gd32l23x_syscfg.h>
#elif defined(CONFIG_SOC_SERIES_GD32M53X)
#include <gd32m53x_syscfg.h>
#elif defined(CONFIG_SOC_SERIES_GD32W51X_F5HC)
#include <gd32w51x_f5hc_syscfg.h>
#endif
