/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32H75E)
#include <gd32h75e_efuse.h>
#elif defined(CONFIG_SOC_SERIES_GD32H7XX)
#include <gd32h7xx_efuse.h>
#elif defined(CONFIG_SOC_SERIES_GD32W51X_F5HC)
#include <gd32w51x_f5hc_efuse.h>
#endif
