/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32A50X)
#include <gd32a50x_trigsel.h>
#elif defined(CONFIG_SOC_SERIES_GD32F50X)
#include <gd32f50x_trigsel.h>
#elif defined(CONFIG_SOC_SERIES_GD32H75E)
#include <gd32h75e_trigsel.h>
#elif defined(CONFIG_SOC_SERIES_GD32H7XX)
#include <gd32h7xx_trigsel.h>
#endif
