/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32E50X)
#include <gd32e50x_tmu.h>
#elif defined(CONFIG_SOC_SERIES_GD32E51X)
#include <gd32e51x_tmu.h>
#elif defined(CONFIG_SOC_SERIES_GD32H7XX)
#include <gd32h7xx_tmu.h>
#endif
