/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32E10X)
#include <gd32e10x_exmc.h>
#elif defined(CONFIG_SOC_SERIES_GD32E50X)
#include <gd32e50x_exmc.h>
#elif defined(CONFIG_SOC_SERIES_GD32E51X)
#include <gd32e51x_exmc.h>
#elif defined(CONFIG_SOC_SERIES_GD32F30X)
#include <gd32f30x_exmc.h>
#elif defined(CONFIG_SOC_SERIES_GD32F403)
#include <gd32f403_exmc.h>
#elif defined(CONFIG_SOC_SERIES_GD32F4XX)
#include <gd32f4xx_exmc.h>
#elif defined(CONFIG_SOC_SERIES_GD32F50X)
#include <gd32f50x_exmc.h>
#elif defined(CONFIG_SOC_SERIES_GD32F527)
#include <gd32f527_exmc.h>
#elif defined(CONFIG_SOC_SERIES_GD32H75E)
#include <gd32h75e_exmc.h>
#elif defined(CONFIG_SOC_SERIES_GD32H7XX)
#include <gd32h7xx_exmc.h>
#elif defined(CONFIG_SOC_SERIES_GD32VF103)
#include <gd32vf103_exmc.h>
#endif
