/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32F50X)
#include <gd32f50x_hau.h>
#elif defined(CONFIG_SOC_SERIES_GD32F527)
#include <gd32f527_hau.h>
#endif
