/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32C11X)
#include <gd32c11x_ctc.h>
#elif defined(CONFIG_SOC_SERIES_GD32E10X)
#include <gd32e10x_ctc.h>
#elif defined(CONFIG_SOC_SERIES_GD32E50X)
#include <gd32e50x_ctc.h>
#elif defined(CONFIG_SOC_SERIES_GD32E51X)
#include <gd32e51x_ctc.h>
#elif defined(CONFIG_SOC_SERIES_GD32F30X)
#include <gd32f30x_ctc.h>
#elif defined(CONFIG_SOC_SERIES_GD32F3X0)
#include <gd32f3x0_ctc.h>
#elif defined(CONFIG_SOC_SERIES_GD32F403)
#include <gd32f403_ctc.h>
#elif defined(CONFIG_SOC_SERIES_GD32F4XX)
#include <gd32f4xx_ctc.h>
#elif defined(CONFIG_SOC_SERIES_GD32F50X)
#include <gd32f50x_ctc.h>
#elif defined(CONFIG_SOC_SERIES_GD32F527)
#include <gd32f527_ctc.h>
#elif defined(CONFIG_SOC_SERIES_GD32H75E)
#include <gd32h75e_ctc.h>
#elif defined(CONFIG_SOC_SERIES_GD32H7XX)
#include <gd32h7xx_ctc.h>
#elif defined(CONFIG_SOC_SERIES_GD32L23X)
#include <gd32l23x_ctc.h>
#elif defined(CONFIG_SOC_SERIES_GD32W51X_F5HC)
#include <gd32w51x_f5hc_ctc.h>
#endif
