/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32A50X)
#include <gd32a50x_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32C11X)
#include <gd32c11x_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32C2X1)
#include <gd32c2x1_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32E10X)
#include <gd32e10x_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32E50X)
#include <gd32e50x_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32E51X)
#include <gd32e51x_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32F30X)
#include <gd32f30x_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32F3X0)
#include <gd32f3x0_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32F403)
#include <gd32f403_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32F4XX)
#include <gd32f4xx_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32F50X)
#include <gd32f50x_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32F527)
#include <gd32f527_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32G5X3)
#include <gd32g5x3_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32H75E)
#include <gd32h75e_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32H7XX)
#include <gd32h7xx_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32L23X)
#include <gd32l23x_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32M53X)
#include <gd32m53x_gpio.h>
#elif defined(CONFIG_SOC_SERIES_GD32VF103)
#include <gd32vf103_gpio.h>
#endif
