/*
 * NOTE: Autogenerated file using gd32headers.py
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_SOC_SERIES_GD32A50X)
#include <gd32a50x_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32E50X)
#include <gd32e50x_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32E51X)
#include <gd32e51x_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32F30X)
#include <gd32f30x_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32F403)
#include <gd32f403_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32F4XX)
#include <gd32f4xx_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32F50X)
#include <gd32f50x_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32F527)
#include <gd32f527_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32G5X3)
#include <gd32g5x3_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32H75E)
#include <gd32h75e_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32H7XX)
#include <gd32h7xx_can.h>
#elif defined(CONFIG_SOC_SERIES_GD32VF103)
#include <gd32vf103_can.h>
#endif
